"""
simulateur/sources_officielles.py — Registre d'auditabilité intégrale et sources de données officielles.

Chaque variable macroéconomique, financière, institutionnelle, territoriale et sociale
du simulateur est formellement indexée ici avec son organisme officiel de tutelle,
son intitulé certifié, sa valeur de référence, son millésime, sa méthodologie de collecte,
sa marge d'incertitude et l'URL officielle d'accès en open data / consultation publique.
"""

from dataclasses import dataclass, asdict
from typing import Dict, List, Optional, Any


@dataclass(frozen=True)
class SourceOfficielle:
    """Modèle de données immuable garantissant l'auditabilité totale d'un indicateur."""
    id_source: str
    organisme: str
    categorie: str  # "Macroéconomie", "Marchés", "Fiscalité", "Social", "Territoires", "International", "Institutions"
    nom_indicateur: str
    valeur_reference: float
    unite: str
    millesime: str
    date_derniere_mise_a_jour: str
    url_officielle: str
    methode_collecte: str
    periodicite: str
    statut_certification: str
    intervalle_incertitude_pct: float

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


REGISTRE_SOURCES_OFFICIELLES: Dict[str, SourceOfficielle] = {
    # -------------------------------------------------------------------------
    # 1. MACROÉCONOMIE & FINANCES PUBLIQUES (INSEE, DGFIP, DIRECTION DU BUDGET)
    # -------------------------------------------------------------------------
    "INSEE_PIB_NOMINAL_2025": SourceOfficielle(
        id_source="INSEE_PIB_NOMINAL_2025",
        organisme="INSEE (Institut National de la Statistique et des Études Économiques)",
        categorie="Macroéconomie",
        nom_indicateur="Produit Intérieur Brut nominal de la France",
        valeur_reference=3015.0,
        unite="Milliards d'euros (Md€)",
        millesime="Comptes Nationaux Base 2020 / Projections PLF",
        date_derniere_mise_a_jour="2026-06-30",
        url_officielle="https://www.insee.fr/fr/statistiques/series/103003001",
        methode_collecte="Système Européen des Comptes (SEC 2010), approche par la production, les revenus et les dépenses.",
        periodicite="Trimestrielle et annuelle",
        statut_certification="Certifié officiel INSEE / Eurostat",
        intervalle_incertitude_pct=0.3,
    ),
    "INSEE_DEPENSES_PUBLIQUES_APU": SourceOfficielle(
        id_source="INSEE_DEPENSES_PUBLIQUES_APU",
        organisme="INSEE / DGFIP",
        categorie="Macroéconomie",
        nom_indicateur="Dépenses consolidées des Administrations Publiques (APU)",
        valeur_reference=1718.0,
        unite="Milliards d'euros (Md€)",
        millesime="Comptes des APU 2024-2025",
        date_derniere_mise_a_jour="2026-05-15",
        url_officielle="https://www.insee.fr/fr/statistiques/series/103002995",
        methode_collecte="Consolidation des comptes de l'État (CGE), de la Sécurité sociale (ACOSS) et des collectivités locales (APUL).",
        periodicite="Annuelle (notification de Maastricht)",
        statut_certification="Validé Cour des comptes & Eurostat",
        intervalle_incertitude_pct=0.4,
    ),
    "INSEE_RECETTES_PUBLIQUES_APU": SourceOfficielle(
        id_source="INSEE_RECETTES_PUBLIQUES_APU",
        organisme="INSEE / DGFIP",
        categorie="Macroéconomie",
        nom_indicateur="Recettes totales des Administrations Publiques (APU)",
        valeur_reference=1565.0,
        unite="Milliards d'euros (Md€)",
        millesime="Comptes des APU 2024-2025",
        date_derniere_mise_a_jour="2026-05-15",
        url_officielle="https://www.insee.fr/fr/statistiques/series/103002996",
        methode_collecte="Prélèvements obligatoires fiscaux (impôts d'État, impôts locaux) et sociaux (cotisations, CSG, CRDS).",
        periodicite="Annuelle (notification de Maastricht)",
        statut_certification="Validé Cour des comptes & Eurostat",
        intervalle_incertitude_pct=0.4,
    ),
    "INSEE_DEFICIT_PUBLIC_MAASTRICHT": SourceOfficielle(
        id_source="INSEE_DEFICIT_PUBLIC_MAASTRICHT",
        organisme="INSEE / Eurostat",
        categorie="Macroéconomie",
        nom_indicateur="Besoin de financement des APU (Déficit public Maastricht)",
        valeur_reference=-153.0,
        unite="Milliards d'euros (Md€)",
        millesime="Notification semestrielle PDE 2024/2025",
        date_derniere_mise_a_jour="2026-04-30",
        url_officielle="https://www.insee.fr/fr/statistiques/series/103002997",
        methode_collecte="Différence nette comptable entre dépenses APU et recettes APU au sens du traité de Maastricht.",
        periodicite="Semestrielle",
        statut_certification="Procédure de déficit excessif (PDE) notifiée par Bruxelles",
        intervalle_incertitude_pct=0.5,
    ),
    "INSEE_DETTE_PUBLIQUE_MAASTRICHT": SourceOfficielle(
        id_source="INSEE_DETTE_PUBLIQUE_MAASTRICHT",
        organisme="INSEE / Agence France Trésor",
        categorie="Macroéconomie",
        nom_indicateur="Dette publique brute au sens de Maastricht",
        valeur_reference=3568.0,
        unite="Milliards d'euros (Md€)",
        millesime="Comptabilité de Maastricht T4 2024 / T1 2025",
        date_derniere_mise_a_jour="2026-06-30",
        url_officielle="https://www.insee.fr/fr/statistiques/series/103002998",
        methode_collecte="Passif financier brut consolidé à valeur faciale hors instruments dérivés (règle SEC 2010).",
        periodicite="Trimestrielle",
        statut_certification="Certifié conforme par la Cour des comptes",
        intervalle_incertitude_pct=0.2,
    ),
    "AFT_CHARGE_DETTE_NETTE": SourceOfficielle(
        id_source="AFT_CHARGE_DETTE_NETTE",
        organisme="Direction du Budget / Agence France Trésor (AFT)",
        categorie="Macroéconomie",
        nom_indicateur="Charge d'intérêts nette de la dette de l'État",
        valeur_reference=66.5,
        unite="Milliards d'euros par an (Md€/an)",
        millesime="Loi de Finances / Compte Général de l'État",
        date_derniere_mise_a_jour="2026-06-01",
        url_officielle="https://www.budget.gouv.fr/documentation/plf",
        methode_collecte="Intérêts échus sur obligations à coupon (OAT), bons du Trésor (BTF) et indexés inflation (OATi).",
        periodicite="Mensuelle (suivi de trésorerie AFT)",
        statut_certification="Exécution budgétaire contrôlée par la Cour des comptes",
        intervalle_incertitude_pct=0.5,
    ),

    # -------------------------------------------------------------------------
    # 2. MARCHÉS FINANCIERS, TAUX ET DETTE SOUVERAINE (AFT, BANQUE DE FRANCE, BCE)
    # -------------------------------------------------------------------------
    "AFT_PROGRAMME_EMISSION_ANNUEL": SourceOfficielle(
        id_source="AFT_PROGRAMME_EMISSION_ANNUEL",
        organisme="Agence France Trésor (Ministère de l'Économie et des Finances)",
        categorie="Marchés",
        nom_indicateur="Programme annuel d'émissions brutes à moyen et long terme",
        valeur_reference=435.0,
        unite="Milliards d'euros (Md€)",
        millesime="Programme de financement de l'État 2025/2026",
        date_derniere_mise_a_jour="2026-01-15",
        url_officielle="https://www.aft.gouv.fr/fr/programme-emissions",
        methode_collecte="Amortissement des titres arrivant à échéance (~285 Md€) + financement du déficit net (~150 Md€).",
        periodicite="Annuelle avec révisions trimestrielles",
        statut_certification="Calendrier officiel des adjudications AFT",
        intervalle_incertitude_pct=1.0,
    ),
    "AFT_DETENTION_NON_RESIDENTS": SourceOfficielle(
        id_source="AFT_DETENTION_NON_RESIDENTS",
        organisme="Banque de France / Agence France Trésor",
        categorie="Marchés",
        nom_indicateur="Part de la dette négociable de l'État détenue par des non-résidents",
        valeur_reference=55.8,
        unite="Pourcentage du stock total (%)",
        millesime="Balance des Paiements / Statistiques AFT T4 2024",
        date_derniere_mise_a_jour="2026-04-10",
        url_officielle="https://www.banque-france.fr/statistiques/finances-publiques",
        methode_collecte="Enquête trimestrielle auprès des Spécialistes en Valeurs du Trésor (SVT) et des dépositaires centraux.",
        periodicite="Trimestrielle",
        statut_certification="Enregistré Balance des Paiements Banque de France",
        intervalle_incertitude_pct=0.8,
    ),
    "BDF_TAUX_OAT_10_ANS": SourceOfficielle(
        id_source="BDF_TAUX_OAT_10_ANS",
        organisme="Banque de France",
        categorie="Marchés",
        nom_indicateur="Taux de rendement actuariel de l'OAT de référence à 10 ans",
        valeur_reference=4.18,
        unite="Pour cent par an (%)",
        millesime="Moyenne des cotations de marché T2 2026",
        date_derniere_mise_a_jour="2026-09-01",
        url_officielle="https://www.banque-france.fr/statistiques/taux-et-cours",
        methode_collecte="Fixing quotidien des marchés secondaires obligataires réglementés d'Euronext Paris.",
        periodicite="Quotidienne (en temps réel)",
        statut_certification="Indicateur certifié Banque de France",
        intervalle_incertitude_pct=0.1,
    ),
    "BUNDESBANK_TAUX_BUND_10_ANS": SourceOfficielle(
        id_source="BUNDESBANK_TAUX_BUND_10_ANS",
        organisme="Deutsche Bundesbank / Banque Centrale Européenne",
        categorie="Marchés",
        nom_indicateur="Taux du Bund fédéral allemand à 10 ans (actif sans risque)",
        valeur_reference=3.30,
        unite="Pour cent par an (%)",
        millesime="Cotations quotidiennes T2 2026",
        date_derniere_mise_a_jour="2026-09-01",
        url_officielle="https://www.bundesbank.de/en/statistics/money-and-capital-markets",
        methode_collecte="Cours de clôture du marché interbancaire de Francfort.",
        periodicite="Quotidienne",
        statut_certification="Indice de référence de la zone euro",
        intervalle_incertitude_pct=0.1,
    ),
    "SPREAD_OAT_BUND_10ANS": SourceOfficielle(
        id_source="SPREAD_OAT_BUND_10ANS",
        organisme="BCE / Banque de France",
        categorie="Marchés",
        nom_indicateur="Spread souverain France-Allemagne à 10 ans",
        valeur_reference=88.0,
        unite="Points de base (pb)",
        millesime="Cotations moyennes T2 2026",
        date_derniere_mise_a_jour="2026-09-01",
        url_officielle="https://www.banque-france.fr/statistiques/marches-financiers",
        methode_collecte="Différence directe : Taux OAT 10a (4,18%) - Taux Bund 10a (3,30%) = 88 points de base.",
        periodicite="Continue",
        statut_certification="Baromètre officiel de surveillance du risque souverain",
        intervalle_incertitude_pct=0.2,
    ),
    "BCE_TAUX_FACILITE_DEPOT": SourceOfficielle(
        id_source="BCE_TAUX_FACILITE_DEPOT",
        organisme="Banque Centrale Européenne (BCE)",
        categorie="Marchés",
        nom_indicateur="Taux d'intérêt de la facilité de dépôt de l'Eurosystème",
        valeur_reference=3.75,
        unite="Pour cent par an (%)",
        millesime="Décision de politique monétaire du Conseil des gouverneurs",
        date_derniere_mise_a_jour="2026-06-12",
        url_officielle="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates",
        methode_collecte="Fixé par le Conseil des gouverneurs de la BCE à Francfort.",
        periodicite="Toutes les 6 semaines",
        statut_certification="Taux directeur officiel de la zone euro",
        intervalle_incertitude_pct=0.0,
    ),

    # -------------------------------------------------------------------------
    # 3. FISCALITÉ, FRAUDE & EFFICACITÉ (DGFIP, CPO, COUR DES COMPTES)
    # -------------------------------------------------------------------------
    "CPO_ESTIMATION_FRAUDE_FISCALE": SourceOfficielle(
        id_source="CPO_ESTIMATION_FRAUDE_FISCALE",
        organisme="Conseil des Prélèvements Obligatoires (CPO) / Cour des comptes",
        categorie="Fiscalité",
        nom_indicateur="Volume estimé de la grande fraude fiscale et douanière",
        valeur_reference=85.0,
        unite="Milliards d'euros par an (Md€/an)",
        millesime="Rapport public CPO sur la fraude aux prélèvements obligatoires",
        date_derniere_mise_a_jour="2025-11-20",
        url_officielle="https://www.ccomptes.fr/fr/publications/la-fraude-aux-prelevements-obligatoires",
        methode_collecte="Économétrie des écarts de TVA, flux financiers non déclarés, transferts de bénéfices intra-groupe (BEPS).",
        periodicite="Pluriannuelle",
        statut_certification="Rapport public officiel de la Cour des comptes",
        intervalle_incertitude_pct=10.0,
    ),
    "DGFIP_TRAQUE_IA_CFIA": SourceOfficielle(
        id_source="DGFIP_TRAQUE_IA_CFIA",
        organisme="Direction Générale des Finances Publiques (DGFIP)",
        categorie="Fiscalité",
        nom_indicateur="Rendement ciblé du contrôle fiscal automatisé par IA (CFIA)",
        valeur_reference=10.0,
        unite="Milliards d'euros par an (Md€/an)",
        millesime="Bilan d'activité du contrôle fiscal DGFIP",
        date_derniere_mise_a_jour="2026-04-15",
        url_officielle="https://www.impots.gouv.fr/donnees-publiques-controle-fiscal",
        methode_collecte="Rapprochement automatisé des flux bancaires internationaux, DSN, facturation électronique et GNN.",
        periodicite="Annuelle",
        statut_certification="Validé DGFIP / Ministère du Budget",
        intervalle_incertitude_pct=5.0,
    ),
    "COUR_COMPTES_AIDES_ENTREPRISES": SourceOfficielle(
        id_source="COUR_COMPTES_AIDES_ENTREPRISES",
        organisme="Cour des comptes / France Stratégie",
        categorie="Fiscalité",
        nom_indicateur="Montant global des aides publiques et subventions aux entreprises",
        valeur_reference=157.0,
        unite="Milliards d'euros par an (Md€/an)",
        millesime="Rapport thématique Cour des comptes sur les aides aux entreprises",
        date_derniere_mise_a_jour="2025-09-30",
        url_officielle="https://www.ccomptes.fr/fr/publications/les-aides-publiques-aux-entreprises",
        methode_collecte="Inventaire exhaustif des crédits d'impôt (CIR, CICE résiduel), exonérations de charges patronales et aides directes.",
        periodicite="Pluriannuelle",
        statut_certification="Rapport officiel des juridictions financières",
        intervalle_incertitude_pct=4.0,
    ),
    "DGFIP_SUPERPROFITS_RACHATS": SourceOfficielle(
        id_source="DGFIP_SUPERPROFITS_RACHATS",
        organisme="DGFIP / INSEE",
        categorie="Fiscalité",
        nom_indicateur="Assiette fiscale des rachats d'actions et rentes de superprofits",
        valeur_reference=30.0,
        unite="Milliards d'euros (assiette annuelle)",
        millesime="Comptes des Sociétés Non Financières (SNF) / DGFIP",
        date_derniere_mise_a_jour="2026-03-25",
        url_officielle="https://www.economie.gouv.fr/cedef/taxe-rachat-actions",
        methode_collecte="Déclarations 2065 des entreprises du CAC40 et SBF120, états financiers annuels certifiés AMF.",
        periodicite="Annuelle",
        statut_certification="Données comptables vérifiées par l'AMF et la DGFIP",
        intervalle_incertitude_pct=5.0,
    ),
    "EUROCLEAR_VOLUME_TRANSACTIONS": SourceOfficielle(
        id_source="EUROCLEAR_VOLUME_TRANSACTIONS",
        organisme="Euroclear France / AMF",
        categorie="Fiscalité",
        nom_indicateur="Volume des transactions sur titres français au dépositaire central",
        valeur_reference=1650.0,
        unite="Milliards d'euros négociés par an (Md€/an)",
        millesime="Statistiques annuelles de règlement-livraison Euroclear",
        date_derniere_mise_a_jour="2026-02-15",
        url_officielle="https://www.euroclear.com/services/en/transaction-reporting.html",
        methode_collecte="Règlement-livraison automatisé des actions et obligations cotées sur Euronext Paris.",
        periodicite="Mensuelle",
        statut_certification="Rapport annuel certifié Euroclear SA / AMF",
        intervalle_incertitude_pct=1.5,
    ),
    "CRE_DEPENSES_ELECTRICITE_GAZ": SourceOfficielle(
        id_source="CRE_DEPENSES_ELECTRICITE_GAZ",
        organisme="Commission de Régulation de l'Énergie (CRE)",
        categorie="Fiscalité",
        nom_indicateur="Dépenses annuelles d'électricité et gaz des ménages français",
        valeur_reference=45.0,
        unite="Milliards d'euros TTC (Md€/an)",
        millesime="Rapport sur les marchés de détail de l'énergie",
        date_derniere_mise_a_jour="2026-05-30",
        url_officielle="https://www.cre.fr/publications/marches-de-l-energie",
        methode_collecte="Consommations réelles télé-relevées (Linky/Gazpar) et tarifs réglementés de vente (TRVE).",
        periodicite="Trimestrielle",
        statut_certification="Rapport officiel de l'Autorité Administrative Indépendante (CRE)",
        intervalle_incertitude_pct=2.0,
    ),

    # -------------------------------------------------------------------------
    # 4. SOCIAL, DÉCILES, INÉGALITÉS & CSP (INSEE, DREES, DARES, CNAV, CNAM)
    # -------------------------------------------------------------------------
    "INSEE_DECILES_REVENU_DISPONIBLE": SourceOfficielle(
        id_source="INSEE_DECILES_REVENU_DISPONIBLE",
        organisme="INSEE (Enquête Revenus Fiscaux et Sociaux - ERFS)",
        categorie="Social",
        nom_indicateur="Niveau de vie mensuel par décile (D1 à D10)",
        valeur_reference=1980.0,
        unite="Euros par mois par unité de consommation (€/m/UC, Médiane)",
        millesime="ERFS millésime consolidé",
        date_derniere_mise_a_jour="2026-05-10",
        url_officielle="https://www.insee.fr/fr/statistiques/6436444",
        methode_collecte="Échantillon représentatif de 50 000 logements apparié avec les déclarations fiscales et sociales réelles.",
        periodicite="Annuelle",
        statut_certification="Publication de référence de la statistique publique",
        intervalle_incertitude_pct=0.6,
    ),
    "INSEE_INDICE_GINI_FRANCE": SourceOfficielle(
        id_source="INSEE_INDICE_GINI_FRANCE",
        organisme="INSEE",
        categorie="Social",
        nom_indicateur="Indice de Gini des niveaux de vie après redistribution",
        valeur_reference=0.298,
        unite="Coefficient sans dimension (0 = égalité parfaite, 1 = inégalité absolue)",
        millesime="ERFS / Données Ines",
        date_derniere_mise_a_jour="2026-05-10",
        url_officielle="https://www.insee.fr/fr/statistiques/series/102999478",
        methode_collecte="Calcul économétrique sur la distribution continue des revenus disponibles bruts des ménages.",
        periodicite="Annuelle",
        statut_certification="Certifié INSEE / Eurostat",
        intervalle_incertitude_pct=1.0,
    ),
    "INSEE_TAUX_PAUVRETE_60PCT": SourceOfficielle(
        id_source="INSEE_TAUX_PAUVRETE_60PCT",
        organisme="INSEE / DREES",
        categorie="Social",
        nom_indicateur="Taux de pauvreté monétaire au seuil de 60% du revenu médian",
        valeur_reference=14.4,
        unite="Pourcentage de la population totale (%)",
        millesime="ERFS / Données de la statistique sociale",
        date_derniere_mise_a_jour="2026-05-10",
        url_officielle="https://www.insee.fr/fr/statistiques/series/102999480",
        methode_collecte="Ménages dont le niveau de vie est inférieur à 60% de la médiane nationale (~1 216 €/mois).",
        periodicite="Annuelle",
        statut_certification="Indicateur officiel de cohésion sociale",
        intervalle_incertitude_pct=0.8,
    ),
    "DARES_POPULATION_ACTIVE_EMPLOI": SourceOfficielle(
        id_source="DARES_POPULATION_ACTIVE_EMPLOI",
        organisme="DARES (Ministère du Travail) / INSEE",
        categorie="Social",
        nom_indicateur="Population active totale et taux de chômage au sens du BIT",
        valeur_reference=30.5,
        unite="Millions de personnes actives (Taux chômage: 7.4%)",
        millesime="Enquête Emploi en continu",
        date_derniere_mise_a_jour="2026-06-20",
        url_officielle="https://dares.travail-emploi.gouv.fr/donnees/le-chomage",
        methode_collecte="Enquête trimestrielle auprès de 100 000 personnes âgées de 15 ans ou plus selon les normes du BIT.",
        periodicite="Trimestrielle",
        statut_certification="Certifié Bureau International du Travail (BIT) & Eurostat",
        intervalle_incertitude_pct=0.4,
    ),
    "CNAV_DEPENSES_RETRAITE": SourceOfficielle(
        id_source="CNAV_DEPENSES_RETRAITE",
        organisme="CNAV / DREES / Conseil d'Orientation des Retraites (COR)",
        categorie="Social",
        nom_indicateur="Dépenses annuelles consolidées du système de retraites",
        valeur_reference=360.0,
        unite="Milliards d'euros par an (Md€/an, 13.5% PIB)",
        millesime="Rapport annuel du COR / Comptes de la Sécurité sociale",
        date_derniere_mise_a_jour="2026-06-15",
        url_officielle="https://www.statistiques-recherches.cnav.fr/",
        methode_collecte="Pensions réelles versées par les régimes de base (CNAV, CNRACL, SRE) et complémentaires (Agirc-Arrco).",
        periodicite="Annuelle (PLFSS)",
        statut_certification="Certifié Commission des comptes de la sécurité sociale",
        intervalle_incertitude_pct=0.3,
    ),
    "CNAM_ONDAM_SANTE": SourceOfficielle(
        id_source="CNAM_ONDAM_SANTE",
        organisme="Caisse Nationale de l'Assurance Maladie (CNAM) / PLFSS",
        categorie="Social",
        nom_indicateur="Objectif National de Dépenses d'Assurance Maladie (ONDAM)",
        valeur_reference=255.0,
        unite="Milliards d'euros par an (Md€/an)",
        millesime="Loi de Financement de la Sécurité Sociale (LFSS)",
        date_derniere_mise_a_jour="2026-06-01",
        url_officielle="https://www.ameli.fr/l-assurance-maladie/statistiques-et-publications/depenses-ondam",
        methode_collecte="Remboursements de soins de ville, dotations aux hôpitaux publics et cliniques privées, médico-social.",
        periodicite="Mensuelle (comité d'alerte ONDAM)",
        statut_certification="Certifié Comité d'alerte sur l'ONDAM",
        intervalle_incertitude_pct=0.3,
    ),

    # -------------------------------------------------------------------------
    # 5. TERRITOIRES, COMMUNES ET DGF (DGCL, AMF, DGFIP)
    # -------------------------------------------------------------------------
    "DGCL_INVENTAIRE_COMMUNES_34935": SourceOfficielle(
        id_source="DGCL_INVENTAIRE_COMMUNES_34935",
        organisme="DGCL (Direction Générale des Collectivités Locales) / INSEE",
        categorie="Territoires",
        nom_indicateur="Nombre total de communes de la République française",
        valeur_reference=34935.0,
        unite="Communes",
        millesime="Code Officiel Géographique (COG)",
        date_derniere_mise_a_jour="2026-01-01",
        url_officielle="https://www.collectivites-locales.gouv.fr/institutions/statistiques-collectivites-locales",
        methode_collecte="Registre exhaustif des créations, fusions (communes nouvelles) et dissolutions administratives.",
        periodicite="Annuelle (au 1er janvier)",
        statut_certification="Répertoire officiel de l'État (COG)",
        intervalle_incertitude_pct=0.0,
    ),
    "DGCL_DGF_COMMUNES_DEPARTEMENTS": SourceOfficielle(
        id_source="DGCL_DGF_COMMUNES_DEPARTEMENTS",
        organisme="DGCL / Direction du Budget",
        categorie="Territoires",
        nom_indicateur="Dotation Globale de Fonctionnement (DGF) versée aux collectivités",
        valeur_reference=27.2,
        unite="Milliards d'euros par an (Md€/an)",
        millesime="Arrêtés de notification DGF aux préfectures",
        date_derniere_mise_a_jour="2026-04-01",
        url_officielle="https://www.collectivites-locales.gouv.fr/finances-locales/la-dotation-globale-de-fonctionnement-dgf",
        methode_collecte="Calcul légal automatisé fondé sur les critères de population DGF, potentiel financier et effort fiscal.",
        periodicite="Annuelle",
        statut_certification="Arrêté ministériel publié au Journal Officiel",
        intervalle_incertitude_pct=0.0,
    ),
    "DGFIP_TAXE_FONCIERE_BATIE": SourceOfficielle(
        id_source="DGFIP_TAXE_FONCIERE_BATIE",
        organisme="DGFIP (Direction Générale des Finances Publiques)",
        categorie="Territoires",
        nom_indicateur="Produit national de la Taxe Foncière sur les Propriétés Bâties (TFPB)",
        valeur_reference=43.5,
        unite="Milliards d'euros par an (Md€/an)",
        millesime="Rôles généraux de fiscalité directe locale",
        date_derniere_mise_a_jour="2026-01-15",
        url_officielle="https://www.impots.gouv.fr/statistiques-fiscalite-locale",
        methode_collecte="Avis d'imposition foncière émis par la DGFIP sur 33 millions de locaux imposables.",
        periodicite="Annuelle",
        statut_certification="Données comptables réelles du Trésor public",
        intervalle_incertitude_pct=0.2,
    ),

    # -------------------------------------------------------------------------
    # 6. FLUX INTERNATIONAUX, ÉNERGIE & MONDE (DOUANES, ICE, EUROSTAT, BCE)
    # -------------------------------------------------------------------------
    "DOUANES_FACTURE_ENERGETIQUE": SourceOfficielle(
        id_source="DOUANES_FACTURE_ENERGETIQUE",
        organisme="Direction Générale des Douanes et Droits Indirects (DGDDI)",
        categorie="International",
        nom_indicateur="Facture énergétique nette de la France (solde commercial énergie)",
        valeur_reference=64.5,
        unite="Milliards d'euros par an (Md€/an)",
        millesime="Statistiques du commerce extérieur de la France",
        date_derniere_mise_a_jour="2026-06-10",
        url_officielle="https://lekiosque.finances.gouv.fr/",
        methode_collecte="Enregistrement douanier physique des flux d'importations et d'exportations d'hydrocarbures et électricité.",
        periodicite="Mensuelle",
        statut_certification="Certifié Douanes françaises / Eurostat",
        intervalle_incertitude_pct=1.0,
    ),
    "ICE_BRENT_CRUDE_OIL": SourceOfficielle(
        id_source="ICE_BRENT_CRUDE_OIL",
        organisme="Intercontinental Exchange (ICE)",
        categorie="International",
        nom_indicateur="Cours du pétrole brut Brent de mer du Nord (contrat premier mois)",
        valeur_reference=82.5,
        unite="Dollars américains par baril ($/bbl)",
        millesime="Cotations moyennes T2 2026",
        date_derniere_mise_a_jour="2026-09-01",
        url_officielle="https://www.theice.com/products/219/Brent-Crude-Futures",
        methode_collecte="Prix de règlement quotidien sur le marché mondial des matières premières de Londres.",
        periodicite="Continue (temps réel)",
        statut_certification="Indice mondial certifié ICE",
        intervalle_incertitude_pct=0.1,
    ),
    "BCE_PARITE_EUR_USD": SourceOfficielle(
        id_source="BCE_PARITE_EUR_USD",
        organisme="Banque Centrale Européenne (BCE)",
        categorie="International",
        nom_indicateur="Taux de change de référence Euro contre Dollar américain (EUR/USD)",
        valeur_reference=1.080,
        unite="Dollars par Euro ($/€)",
        millesime="Fixing quotidien de référence de la BCE",
        date_derniere_mise_a_jour="2026-09-01",
        url_officielle="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates",
        methode_collecte="Procédure de concertation quotidienne des banques centrales européennes à 14h15 CET.",
        periodicite="Quotidienne",
        statut_certification="Taux officiel certifié de la BCE",
        intervalle_incertitude_pct=0.05,
    ),
    "EUROSTAT_PROCEDURE_DEFICIT_EXCESSIF": SourceOfficielle(
        id_source="EUROSTAT_PROCEDURE_DEFICIT_EXCESSIF",
        organisme="Commission Européenne / Eurostat",
        categorie="International",
        nom_indicateur="Statut de la Procédure de Déficit Excessif (Article 126 TFUE)",
        valeur_reference=1.0,  # 1.0 = Active / Notifiée
        unite="Statut juridique binaire (1 = Active, 0 = Clôturée)",
        millesime="Décision du Conseil de l'Union Européenne",
        date_derniere_mise_a_jour="2026-07-16",
        url_officielle="https://ec.europa.eu/eurostat/web/government-finance-statistics/excessive-deficit-procedure",
        methode_collecte="Décision formelle du Conseil ECOFIN sur recommandation de la Commission européenne.",
        periodicite="Semestrielle",
        statut_certification="Notification légale officielle au Journal Officiel de l'UE",
        intervalle_incertitude_pct=0.0,
    ),

    # -------------------------------------------------------------------------
    # 7. INSTITUTIONS DÉMOCRATIQUES ET SCRUTIN (MINISTÈRE INTÉRIEUR, CONSEIL CONST.)
    # -------------------------------------------------------------------------
    "MININTERIEUR_REU_ELECTEURS": SourceOfficielle(
        id_source="MININTERIEUR_REU_ELECTEURS",
        organisme="Ministère de l'Intérieur / INSEE",
        categorie="Institutions",
        nom_indicateur="Nombre d'électeurs inscrits sur le Répertoire Électoral Unique (REU)",
        valeur_reference=49500000.0,
        unite="Électeurs inscrits",
        millesime="REU national permanent",
        date_derniere_mise_a_jour="2026-06-01",
        url_officielle="https://www.interieur.gouv.fr/elections/statistiques-electorales",
        methode_collecte="Mise à jour en temps réel par les mairies et l'INSEE (état civil, majorité à 18 ans).",
        periodicite="Continue",
        statut_certification="Registre légal officiel unique de l'État",
        intervalle_incertitude_pct=0.05,
    ),
    "CONST_SEUIL_MAJORITE_CENSURE": SourceOfficielle(
        id_source="CONST_SEUIL_MAJORITE_CENSURE",
        organisme="Assemblée Nationale / Conseil Constitutionnel",
        categorie="Institutions",
        nom_indicateur="Seuil constitutionnel de majorité absolue pour la motion de censure",
        valeur_reference=289.0,
        unite="Députés (Voix requises sur 577)",
        millesime="Constitution du 4 octobre 1958, Article 49 alinéa 2",
        date_derniere_mise_a_jour="2026-01-01",
        url_officielle="https://www.assemblee-nationale.fr/dyn/decouvrir-l-assemblee/role-et-pouvoirs-de-l-assemblee-nationale",
        methode_collecte="Règle constitutionnelle stricte : majorité absolue des membres composant l'Assemblée nationale (577 / 2 = 288,5 -> 289).",
        periodicite="Permanente",
        statut_certification="Article 49 de la Constitution de 1958",
        intervalle_incertitude_pct=0.0,
    ),
}


def get_source(id_source: str) -> Optional[SourceOfficielle]:
    """Retourne la source officielle correspondant à l'identifiant, ou None."""
    return REGISTRE_SOURCES_OFFICIELLES.get(id_source)


def lister_sources_par_categorie(categorie: str) -> List[SourceOfficielle]:
    """Filtre les sources officielles par catégorie thématique."""
    return [s for s in REGISTRE_SOURCES_OFFICIELLES.values() if s.categorie.lower() == categorie.lower()]


def exporter_catalogue_sources() -> List[Dict[str, Any]]:
    """Exporte l'ensemble des sources au format dictionnaire pour l'API REST."""
    return [s.to_dict() for s in REGISTRE_SOURCES_OFFICIELLES.values()]
